import json
import smtplib
import time
from google import genai
import markdown
import streamlit as st
from modules.state import save_fundamental_reports, save_market_briefings


# ==========================================
# 1. BULLETPROOF PDF GENERATOR ENGINE
# ==========================================
def create_pdf_bytes(ticker, report_md):
    try:
        from fpdf import FPDF
    except ImportError:
        return report_md.encode("utf-8")

    def sanitize_for_pdf(text):
        if not text:
            return ""
        replacements = {
            "🟢": "[PASS] ",
            "🔴": "[FAIL] ",
            "🟡": "[WATCH] ",
            "⚠️": "[WARN] ",
            "🚀": "[CATALYST] ",
            "⚪": "[N/A] ",
            "🟣": "[REVIEW] ",
            "📊": "",
            "🏥": "",
            "📈": "",
            "🔥": "",
            "📋": "",
            "🧠": "",
            "⭐": "",
            "🎯": "[TARGET] ",
            "🚨": "[CIRCUIT] ",
            "₹": "Rs. ",
            "—": "-",
            "–": "-",
            "“": '"',
            "”": '"',
            "‘": "'",
            "’": "'",
            "•": "-",
            "…": "...",
            "**": "",  # Strip markdown bolding
            "__": "",  # Strip markdown alternative bolding
            "* ": "- ", # Clean list markers
        }
        for k, v in replacements.items():
            text = text.replace(k, v)
        return text.encode("latin-1", "replace").decode("latin-1")

    class PDF(FPDF):
        def header(self):
            self.set_font("Helvetica", "B", 10)
            self.set_text_color(100, 100, 100)
            self.cell(
                0,
                8,
                sanitize_for_pdf(f"MINERVINI FUNDAMENTAL AI REPORT - {ticker}"),
                ln=True,
                align="R",
            )
            self.line(10, 16, 200, 16)
            self.ln(4)

        def footer(self):
            self.set_y(-15)
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(128, 128, 128)
            self.cell(
                0,
                10,
                sanitize_for_pdf(
                    f"Page {self.page_no()} | Generated by India Equities Screener Studio"
                ),
                align="C",
            )

    try:
        pdf = PDF()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)

        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(
            0,
            8,
            sanitize_for_pdf(f"{ticker} Fundamental Analysis Report"),
            ln=True,
            align="L",
        )
        pdf.ln(2)

        pdf.set_font("Helvetica", size=9)
        for line in report_md.split("\n"):
            line_str = sanitize_for_pdf(line.strip())
            if not line_str:
                pdf.ln(1.5)
                continue
            if line_str.startswith("#### ") or line_str.startswith("### "):
                pdf.set_font("Helvetica", "B", 11)
                pdf.set_text_color(20, 50, 120)
                pdf.cell(0, 6, line_str.replace("#", "").strip(), ln=True)
                pdf.set_font("Helvetica", size=9)
                pdf.set_text_color(0, 0, 0)
            elif line_str.startswith("## ") or line_str.startswith("# "):
                pdf.set_font("Helvetica", "B", 12)
                pdf.set_text_color(15, 23, 42)
                pdf.cell(0, 7, line_str.replace("#", "").strip(), ln=True)
                pdf.set_font("Helvetica", size=9)
                pdf.set_text_color(0, 0, 0)
            else:
                pdf.multi_cell(0, 4.5, line_str)
                pdf.ln(0.5)

        return bytes(pdf.output())
    except Exception:
        return report_md.encode("utf-8")


# ==========================================
# 2. GEMINI LIVE SEARCH GROUNDING ENGINE
# ==========================================
def run_gemini_fundamental_analysis(
    ticker_input, reports_store=None, status_log=None
):
    gemini_key = st.secrets.get("GEMINI_API_KEY", "")
    email_addr = st.secrets.get("EMAIL_ADDRESS", "")
    email_pass = st.secrets.get("EMAIL_APP_PASSWORD", "")

    if not gemini_key:
        if status_log:
            status_log.error("❌ Missing GEMINI_API_KEY in Streamlit Secrets!")
        return None

    client = genai.Client(api_key=gemini_key)

    clean_ticker = (
        ticker_input.split(":")[-1].strip().upper()
        if ":" in str(ticker_input)
        else str(ticker_input).strip().upper()
    )

    if status_log:
        status_log.write(f"🌐 **{clean_ticker}:** Utilizing Gemini Live Web Search Grounding to extract latest metrics and concall catalysts...")

    prompt = f"""
You are an uncompromising, strict Mark Minervini-style fundamental analyst. 
Your sole objective is to analyze the Indian stock **{clean_ticker} (NSE/BSE)** to determine if it meets Minervini's "Superperformance" criteria.

### CRITICAL INSTRUCTION: LIVE WEB GROUNDING
You MUST use your Google Search tool to find the most up-to-date information for **{clean_ticker}**. Search specifically for:
1. The most recent Quarterly Earnings Results (QoQ and YoY EPS/Sales growth).
2. Recent Earnings Call Transcript summaries, Management Guidance, and Concall highlights.
3. Analyst reports or recent financial news regarding upcoming catalysts, order books, and institutional shareholding.

### DATA & GROUND TRUTH RULES
1. Rely ONLY on official, trusted sources (BSE/NSE filings, Trendlyne, Screener, transcripts).
2. Do not speculate, calculate unstated assumptions, or fill gaps from external knowledge.
3. If any metric or fact is missing from the search results, write explicitly: "Not available."

### STRICT CATALYST & VERDICT RULES (CRITICAL)
- **NO CATALYST = NO PASS:** Even if YoY earnings and sales growth are >20%, you CANNOT award a 🟢 PASS if there is no explicit, forward-looking fundamental catalyst identified in recent news, transcripts, or guidance. If growth is strong but no trigger is found, the maximum grade is 🟡 WATCHLIST.
- **SECTOR-ADAPTIVE CATALYST SEARCH:** Evaluate based on the business model:
  - *Manufacturing/Infra:* CapEx, plant commissioning, order book.
  - *Financials:* Credit growth, NIM expansion, AUM growth.
  - *Tech/SaaS:* Large deal wins (TCV), margin recovery.
  - *Consumer:* Volume growth, SSSG.
  - *Pharma:* FDA approvals, new launches.

---

### OUTPUT FORMAT & VISUAL HIERARCHY

#### 1. HEADER & INSTANT VERDICT
Provide the company name and an instant decision verdict:
- **MINERVINI FUNDAMENTAL VERDICT:** [Insert 🟢 PASS / 🟡 WATCHLIST / 🔴 FAIL]
- **🚀 PRIMARY CATALYST / BREAKOUT TRIGGER:** [State in 1-2 BOLD sentences the exact forward-looking trigger driving this stock based on your live search. If NONE found, state: "⚠️ NO CLEAR FORWARD CATALYST DETECTED"].
- **VERDICT LOGIC:** [1-2 sentence justification].
  - 🟢 **PASS:** Available YoY Sales & EPS > 20%, positive acceleration, AND a clear, validated forward catalyst.
  - 🟡 **WATCHLIST:** Strong growth but NO clear catalyst, OR a Catalyst Override applied.
  - 🔴 **FAIL:** Confirmed Sales/EPS growth < 20%, decelerating growth, or major red flags.

#### 2. SUPERPERFORMANCE SCORECARD
Present this quick-scan summary table (Use "N/A - Data not found" if missing):

| Core Pillar | Status | Key Metric / Reason |
| :--- | :---: | :--- |
| **1. Growth Velocity (Code 33)** | [🟢 / 🟡 / 🔴 / ⚪ N/A] | [1-line summary of recent EPS & Sales YoY trajectory] |
| **2. Forward Catalyst & Triggers** | [🟢 / 🟡 / 🔴 / ⚪ N/A] | [1-line summary of sector-specific catalyst from recent guidance] |
| **3. Earnings Quality & Red Flags**| [🟢 / 🟡 / 🔴 / ⚪ N/A] | [1-line summary of margins, debt, or cash flow concerns] |

#### 3. BOTTOM LINE UP FRONT (BLUF)
- **Top Fundamental Strengths:**
  - [Bullet 1]
  - [Bullet 2]
  - [Bullet 3]
- **Top Red Flags / Concerns:**
  - [Bullet 1]
  - [Bullet 2]
  - [Bullet 3]

---

### DETAILED ANALYSIS BREAKDOWN

Use visual status icons at the start of each bullet: 🟢 Clear Pass | 🔴 Fail/Red Flag | 🟡 Mixed | ⚠️ Warning | ⚪ Data not found
Bold ONLY key metrics, figures, and definitive "Yes/No" answers.

#### SECTION 1: Growth Velocity (The Engine)
* **Latest Quarter YoY Growth:** Exact % values for EPS and Sales growth based on the latest available quarter.
* **Code 33 Acceleration:** Are EPS, Sales, and Margins accelerating? 
* **Margin Dynamics:** Are Net and Operating Profit Margins expanding YoY?
* **Management Guidance:** What did management outline for the next 2-4 quarters in their most recent concall/interview?
* **Annual Track Record:** Annual EPS growth rate? Are current FY estimates projected to reach a new all-time high?

#### SECTION 2: Sector-Adaptive Catalyst & Forward Triggers
* **Primary Sector Catalyst:** Identify the primary growth driver currently active.
* **Catalyst Magnitude & Timeline:** Is this a game-changing trigger taking effect soon?
* **Institutional Sponsorship (FII/DII Trend):** Did FII, DII, or Mutual Fund shareholding increase in the most recent quarter compared to the previous quarter? (Yes / No / Data Missing)
* **Market Leadership:** Is the company a market leader (#1 or #2 in its niche) or gaining market share?
* **Competitive Advantage:** Is the growth model scalable?

#### SECTION 3: Quality of Earnings & Red Flags
* ⚠️ **Inventory / Receivables vs Sales:** Any divergence reported in recent financials?
* **Source of Profit:** Is EPS driven by Top Line revenue or purely cost-cutting?
* **Tax Rate Distortion:** Was there an artificial boost to EPS from a lower effective tax rate?
* **Cash Flow vs. Earnings:** Has Operating Cash Flow (CFO) diverged negatively from Net Profit?
* **Debt Load & Solvency:** Any major debt concerns flagged by analysts recently?
"""

    try:
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt,
            config={
                "tools": [{"google_search": {}}],
                "temperature": 0.2,
            }
        )
        
        analysis_text = response.text

        verdict_line = ""
        for line in analysis_text.upper().split("\n"):
            if "MINERVINI FUNDAMENTAL VERDICT:" in line or "VERDICT:" in line:
                verdict_line = line
                break

        if "PASS" in verdict_line or "🟢" in verdict_line:
            verdict = "🟢 PASS"
        elif "WATCHLIST" in verdict_line or "🟡" in verdict_line:
            verdict = "🟡 WATCHLIST"
        elif "FAIL" in verdict_line or "🔴" in verdict_line:
            verdict = "🔴 FAIL"
        else:
            verdict = "⚪ Review Needed"

        today_str = time.strftime("%Y-%m-%d")
        report_entry = {
            "ticker": clean_ticker,
            "verdict": verdict,
            "date": today_str,
            "report_md": analysis_text,
        }

        if reports_store is not None:
            reports_store[clean_ticker] = report_entry
            save_fundamental_reports(reports_store)
        else:
            st.session_state.fundamental_reports[clean_ticker] = report_entry
            save_fundamental_reports(st.session_state.fundamental_reports)

        if status_log:
            status_log.write(
                f"✅ **{clean_ticker}:** Analysis complete! Verdict ->"
                f" **{verdict}** (Saved to Gist)"
            )

        if email_addr and email_pass:
            try:
                from email.mime.multipart import MIMEMultipart
                from email.mime.text import MIMEText

                html_text = markdown.markdown(
                    analysis_text, extensions=["tables"]
                )
                subject = f"{clean_ticker} - {verdict}"

                msg = MIMEMultipart("alternative")
                msg["From"] = email_addr
                msg["To"] = email_addr
                msg["Subject"] = subject

                part1 = MIMEText(analysis_text, "plain")
                part2 = MIMEText(html_text, "html")
                msg.attach(part1)
                msg.attach(part2)

                server = smtplib.SMTP("smtp.gmail.com", 587)
                server.starttls()
                server.login(email_addr, email_pass)
                server.send_message(msg)
                server.quit()
                if status_log:
                    status_log.write(f"📧 Email report delivered for {clean_ticker}.")
            except Exception as mail_err:
                if status_log:
                    status_log.write(f"⚠️ Email dispatch warning: {mail_err}")

        return report_entry
        
    except Exception as e:
        if status_log:
            status_log.error(f"❌ **{clean_ticker}:** Gemini Search Analysis failed -> {e}")
        return None


# ==========================================
# 3. REPORT MODAL DIALOG
# ==========================================
@st.dialog("🧠 Minervini Fundamental AI Analyst", width="large")
def show_fundamental_modal(ticker_symbol):
    clean_sym = (
        ticker_symbol.split(":")[-1].strip().upper()
        if ":" in str(ticker_symbol)
        else str(ticker_symbol).strip().upper()
    )
    rep = st.session_state.fundamental_reports.get(clean_sym)

    if not rep:
        st.info(
            f"No stored report for **{clean_sym}**. Check its row in the table"
            " below and click 'Analyze Selected'!"
        )
    else:
        st.subheader(f"📊 {clean_sym} — {rep.get('verdict', 'N/A')}")
        st.caption(
            f"📅 Generated On: **{rep.get('date', 'N/A')}** | 💡 Live Web Grounded Report"
        )
        st.markdown("---")
        st.markdown(rep.get("report_md", ""))
        st.markdown("---")

        col_pdf, col_re = st.columns([1, 1])

        with col_pdf:
            pdf_bytes = create_pdf_bytes(clean_sym, rep.get("report_md", ""))
            st.download_button(
                label=f"📥 Download {clean_sym} Report (PDF)",
                data=pdf_bytes,
                file_name=f"{clean_sym}_Minervini_Fundamental_Report.pdf",
                mime="application/pdf",
                use_container_width=True,
                type="primary",
            )

        with col_re:
            if st.button(
                "🔄 Re-Analyze & Overwrite (Quarterly Refresh)",
                type="secondary",
                use_container_width=True,
            ):
                with st.spinner(
                    f"📡 Fetching live data & replacing {clean_sym} report..."
                ):
                    updated_rep = run_gemini_fundamental_analysis(
                        clean_sym, st.session_state.fundamental_reports
                    )
                    if updated_rep:
                        st.success(
                            "✅ Old report replaced with latest data!"
                        )
                        st.rerun()


# ==========================================
# 4. GEMINI AI SITUATIONAL AWARENESS ENGINE
# ==========================================
def run_gemini_market_awareness(
    df_mm, df_heat, df_rot, scan_summary_dict=None, status_log=None
):
    gemini_key = st.secrets.get("GEMINI_API_KEY", "")
    if not gemini_key:
        if status_log:
            status_log.error("❌ Missing GEMINI_API_KEY in Streamlit Secrets!")
        return None

    client = genai.Client(api_key=gemini_key)

    mm_text = "No Market Monitor Data"
    if not df_mm.empty:
        mm_slice = df_mm.head(10).to_string(index=False)
        mm_text = f"NSE Market Monitor (Last 10 Trading Days):\n{mm_slice}"

    heat_text = "No Sector Heatmap Data"
    if not df_heat.empty:
        heat_slice = df_heat.to_string(index=False)
        heat_text = f"27-Sector CAN SLIM RS Heatmap & Rank Velocities:\n{heat_slice}"

    rot_text = "No Rotation Tracker Data"
    if not df_rot.empty:
        rot_slice = df_rot.head(10).to_string(index=False)
        rot_text = (
            "65-Day Historical Sector RS Ranks (Last 10 Days Trend):\n"
            f" {rot_slice}"
        )

    scan_text = "No Active Screener Scan Summary Available"
    if scan_summary_dict:
        sec_str = json.dumps(scan_summary_dict.get("sectors", {}), indent=2)
        ind_str = json.dumps(scan_summary_dict.get("industries", {}), indent=2)
        scan_text = (
            f"Active Screener Scan Leadership Breakdown:\n- Top Sectors passing"
            f" filters:\n{sec_str}\n- Top Basic Industries passing"
            f" filters:\n{ind_str}"
        )

    prompt = f"""
You are a Senior Institutional Market Strategist and Mark Minervini / Stan Weinstein Market Regime Specialist for Indian Equities (NSE/BSE).

Your sole objective is to analyze the provided multi-day market breadth tables, sector relative strength heatmaps, 65-day rotation rank trends, and active CAN SLIM screener setup concentrations to produce an uncompromising, actionable **Daily Market & Sector Situational Awareness Briefing**.

---

### QUANTITATIVE DATA INPUTS:

{mm_text}

---

{heat_text}

---

{rot_text}

---

{scan_text}

---

### MANDATORY REPORT TEMPLATE & STRUCTURAL REQUIREMENTS:

Generate the report following this exact markdown template structure without skipping any section:

# 🏥 DAILY MARKET & SECTOR SITUATIONAL AWARENESS BRIEFING

#### 1. EXECUTIVE SUMMARY & MARKET REGIME
- **CURRENT MARKET REGIME:** [Select ONE: 🟢 CONFIRMED UPTREND / 🟡 POWERED UPTREND (CAUTION) / 🟠 RANGEBOUND / CHOPPY / 🔴 MARKET UNDER PRESSURE / BEARISH REVERSAL]
- **SETUP SUITABILITY MATRIX:**
  - 🚀 **Momentum Breakout Setups:** [HIGHLY CONDUCTIVE / SELECTIVE (HIGH QUALITY ONLY) / AVOID]
  - 📉 **Pullback / Re-test Setups:** [HIGHLY CONDUCTIVE / SELECTIVE / AVOID]
  - 🔄 **Consolidation / Base Setups:** [HIGHLY CONDUCTIVE / SELECTIVE / AVOID]
- **OVERALL MARKET STATE SUMMARY:** [3-4 sentences synthesizing price action, breadth thrusts, A/D ratio, and % of stocks above key moving averages over the past 5-10 days].

---

#### 2. MARKET BREADTH & HEALTH SYNTHESIS
- **Trend & Moving Average Participation:** Analyze the trend in stocks >20 EMA, >50 SMA, and >200 SMA.
- **Thrust & Volume Expansion:** Interpret the 5-Day & 10-Day Thrust Ratios, A/D Ratio, and Volume Breadth.
- **Expansion vs. Contraction:** Evaluate 52W Highs vs. 52W Lows and 4% Up vs. Down movers over the past week.

---

#### 3. SECTOR MOMENTUM & ROTATION RADAR
- 🟢 **LEADERSHIP SECTORS (Top Focus for Long Setups):** Detail the top 3-5 sectors ranking #1-5 with positive rank velocity and RS > benchmark.
- 🚀 **EMERGING / ACCELERATING SECTORS:** Detail sectors jumping ranks rapidly in 5D/10D/21D rank velocity.
- ⚠️ **FADING / WEAKENING SECTORS:** Detail sectors dropping in relative strength or breaking below 50 SMA.
- 🔴 **AVOID / BEARISH SECTORS:** Bottom ranked sectors or sectors showing sharp negative rank velocity.

---

#### 4. ACTIVE SCREENER SCAN CLUSTER ANALYSIS
- **Sector Concentration:** Analyze where the highest percentage of passing stocks originate based on the scan summary data.
- **Industry Sub-Clusters:** Identify specific basic industries showing stock setup clusters (e.g., Industrial Manufacturing, Capital Goods, Pharma).

---

#### 5. ACTIONABLE NEXT-DAY EXECUTION PLAN
- 🛡️ **Allowed Risk Per Trade:** [State exact equity risk rule, e.g., 0.5% - 0.75% per trade].
- 💰 **Maximum Portfolio Deployment / Cash Buffer:** [State cash allocation rule, e.g., 80%-100% deployed vs 30% cash buffer].
- 🎯 **Primary Focus Sectors & Industries for Tomorrow:** [List exact 2-3 sectors and basic industries to screen for buys].
- 🚨 **Key Invalidation Levels & Danger Triggers:** [State exact breadth or Nifty 500 thresholds that would signal stopping new buys].
"""

    try:
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=[prompt],
            config={"service_tier": "flex", "http_options": {"timeout": 900000}},
        )
        briefing_text = response.text
        today_str = time.strftime("%Y-%m-%d")

        entry = {
            "date": today_str,
            "briefing_md": briefing_text,
        }

        st.session_state.market_briefings[today_str] = entry
        save_market_briefings(st.session_state.market_briefings)

        if status_log:
            status_log.write(
                f"✅ **Market Briefing Generated for {today_str}** (Saved to Gist)"
            )

        return entry
    except Exception as e:
        if status_log:
            status_log.error(f"❌ Failed to generate Market Briefing -> {e}")
        return None
