import glob
import json
import os
import smtplib
import time
from urllib.parse import urljoin
from bs4 import BeautifulSoup
from google import genai
import markdown
import requests
import streamlit as st
from modules.state import save_fundamental_reports, save_market_briefings

def create_pdf_bytes(ticker, report_md):
    try:
        from fpdf import FPDF
    except ImportError:
        return report_md.encode("utf-8")

    def sanitize_for_pdf(text):
        if not text:
            return ""
        replacements = {
            "🟢": "[PASS] ", "🔴": "[FAIL] ", "🟡": "[WATCH] ", "⚠️": "[WARN] ",
            "🚀": "[CATALYST] ", "⚪": "[N/A] ", "🟣": "[REVIEW] ", "📊": "",
            "🏥": "", "📈": "", "🔥": "", "📋": "", "🧠": "", "⭐": "",
            "🎯": "[TARGET] ", "🚨": "[CIRCUIT] ", "₹": "Rs. ", "—": "-",
            "–": "-", "“": '"', "”": '"', "‘": "'", "’": "'", "•": "*", "…": "...",
        }
        for k, v in replacements.items():
            text = text.replace(k, v)
        return text.encode("latin-1", "replace").decode("latin-1")

    class PDF(FPDF):
        def header(self):
            self.set_font("Helvetica", "B", 10)
            self.set_text_color(100, 100, 100)
            self.cell(0, 8, sanitize_for_pdf(f"MINERVINI FUNDAMENTAL AI REPORT - {ticker}"), ln=True, align="R")
            self.line(10, 16, 200, 16)
            self.ln(4)

        def footer(self):
            self.set_y(-15)
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(128, 128, 128)
            self.cell(0, 10, sanitize_for_pdf(f"Page {self.page_no()} | Generated by India Equities Screener Studio"), align="C")

    try:
        pdf = PDF()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(0, 8, sanitize_for_pdf(f"{ticker} Fundamental Analysis Report"), ln=True, align="L")
        pdf.ln(2)

        pdf.set_font("Helvetica", size=9)
        for line in report_md.split("\n"):
            line_str = sanitize_for_pdf(line.strip())
            if not line_str:
                pdf.ln(1.5)
                continue
            if line_str.startswith("#### ") or line_str.startswith("### "):
                pdf.set_font("Helvetica", "B", 11)
                pdf.set_text_color(20, 50, 120)
                pdf.cell(0, 6, line_str.replace("#", "").strip(), ln=True)
                pdf.set_font("Helvetica", size=9)
                pdf.set_text_color(0, 0, 0)
            elif line_str.startswith("## ") or line_str.startswith("# "):
                pdf.set_font("Helvetica", "B", 12)
                pdf.set_text_color(15, 23, 42)
                pdf.cell(0, 7, line_str.replace("#", "").strip(), ln=True)
                pdf.set_font("Helvetica", size=9)
                pdf.set_text_color(0, 0, 0)
            else:
                pdf.multi_cell(0, 4.5, line_str)
                pdf.ln(0.5)

        return bytes(pdf.output())
    except Exception:
        return report_md.encode("utf-8")

def run_gemini_fundamental_analysis(ticker_input, reports_store=None, status_log=None):
    gemini_key = st.secrets.get("GEMINI_API_KEY", "")
    screener_sid = st.secrets.get("SCREENER_SESSION_ID", "")
    email_addr = st.secrets.get("EMAIL_ADDRESS", "chethanshivaraju7@gmail.com")
    email_pass = st.secrets.get("EMAIL_APP_PASSWORD", "")

    if not gemini_key:
        if status_log: status_log.error("❌ Missing GEMINI_API_KEY in Streamlit Secrets!")
        return None

    client = genai.Client(api_key=gemini_key)
    headers = {"User-Agent": "Mozilla/5.0", "Referer": "https://www.screener.in/"}
    cookies = {"sessionid": screener_sid}

    clean_ticker = ticker_input.split(":")[-1].strip().upper() if ":" in str(ticker_input) else str(ticker_input).strip().upper()
    download_dir = "documents"
    os.makedirs(download_dir, exist_ok=True)
    for f in glob.glob(f"{download_dir}/*"): os.remove(f)

    url = f"https://www.screener.in/company/{clean_ticker}/consolidated/"

    try:
        if status_log: status_log.write(f"📡 **{clean_ticker}:** Accessing Screener.in page...")
        response = requests.get(url, headers=headers, cookies=cookies, timeout=20)
        if response.status_code != 200:
            if status_log: status_log.error(f"❌ **{clean_ticker}:** Could not access Screener.in page (HTTP {response.status_code}).")
            return None

        soup = BeautifulSoup(response.content, "html.parser")
        documents_section = soup.find(id="documents")
        if not documents_section:
            if status_log: status_log.warning(f"⚠️ **{clean_ticker}:** No documents section found on Screener.in.")
            return None

        ars, transcripts, ppts = [], [], []
        links = documents_section.find_all("a", href=True)
        for link in links:
            href = link["href"]
            text = link.get_text(strip=True).lower()
            if "financial year" in text or "annual report" in text: ars.append(("Annual Report", href))
            elif text == "transcript": transcripts.append(("Transcript", href))
            elif text == "ppt": ppts.append(("PPT", href))

        state = {"count": 0, "urls": set()}
        def try_download(text, href):
            if href in state["urls"]: return False
            full_url = href if href.startswith("http") else urljoin("https://www.screener.in", href)
            try:
                doc_response = requests.get(full_url, headers=headers, cookies=cookies, timeout=30, allow_redirects=True)
                if b"%PDF" in doc_response.content[:100]:
                    file_name = f"screener_doc_{state['count'] + 1}.pdf"
                    file_path = os.path.join(download_dir, file_name)
                    with open(file_path, "wb") as f: f.write(doc_response.content)
                    state["count"] += 1
                    state["urls"].add(href)
                    time.sleep(1)
                    return True
            except Exception: pass
            return False

        ar_count, tr_count, ppt_count = 0, 0, 0
        for t, h in ars:
            if ar_count >= 1: break
            if try_download("Annual Report", h): ar_count += 1
        for t, h in transcripts:
            if tr_count >= 4: break
            if try_download("Transcript", h): tr_count += 1
        for t, h in ppts:
            if ppt_count >= 4: break
            if try_download("PPT", h): ppt_count += 1

        pdf_files = glob.glob(f"{download_dir}/*.pdf")
        if not pdf_files:
            if status_log: status_log.error(f"❌ **{clean_ticker}:** Could not download any valid PDF reports.")
            return None

        if status_log: status_log.write(f"🤖 Uploading {len(pdf_files)} PDFs to Gemini 2.5 Flash...")
        uploaded_files = [client.files.upload(file=f) for f in pdf_files]
        for f in uploaded_files:
            while True:
                file_info = client.files.get(name=f.name)
                if "ACTIVE" in str(file_info.state).upper(): break
                time.sleep(3)

        prompt = """
You are an uncompromising Mark Minervini-style fundamental analyst. Analyze the provided Annual Report, Investor Presentations, and Transcripts for Superperformance criteria.
Evaluate YoY EPS & Sales growth (>20%), forward catalysts, margins, and earnings quality red flags.
Provide an instant verdict (🟢 PASS / 🟡 WATCHLIST / 🔴 FAIL), scorecard, BLUF summary, and detailed sections.
        """
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=[prompt] + uploaded_files,
            config={"service_tier": "flex", "http_options": {"timeout": 900000}},
        )
        analysis_text = response.text
        verdict = "PASS 🟢" if "PASS" in analysis_text.upper() else ("WATCHLIST 🟡" if "WATCHLIST" in analysis_text.upper() else "FAIL 🔴")
        today_str = time.strftime("%Y-%m-%d")

        report_entry = {"ticker": clean_ticker, "verdict": verdict, "date": today_str, "report_md": analysis_text}
        store = reports_store if reports_store is not None else st.session_state.fundamental_reports
        store[clean_ticker] = report_entry
        save_fundamental_reports(store)

        if email_addr and email_pass:
            try:
                from email.mime.multipart import MIMEMultipart
                from email.mime.text import MIMEText
                msg = MIMEMultipart("alternative")
                msg["From"] = email_addr
                msg["To"] = email_addr
                msg["Subject"] = f"{clean_ticker} - {verdict}"
                msg.attach(MIMEText(analysis_text, "plain"))
                msg.attach(MIMEText(markdown.markdown(analysis_text, extensions=["tables"]), "html"))
                server = smtplib.SMTP("smtp.gmail.com", 587)
                server.starttls()
                server.login(email_addr, email_pass)
                server.send_message(msg)
                server.quit()
            except Exception: pass

        return report_entry
    except Exception as e:
        if status_log: status_log.error(f"❌ **{clean_ticker}:** Analysis failed -> {e}")
        return None

def run_gemini_market_awareness(df_mm, df_heat, df_rot, scan_summary_dict=None, status_log=None):
    gemini_key = st.secrets.get("GEMINI_API_KEY", "")
    if not gemini_key: return None
    client = genai.Client(api_key=gemini_key)

    mm_text = df_mm.head(10).to_string(index=False) if not df_mm.empty else "No MM Data"
    heat_text = df_heat.to_string(index=False) if not df_heat.empty else "No Heat Data"
    rot_text = df_rot.head(10).to_string(index=False) if not df_rot.empty else "No Rot Data"

    prompt = f"""
You are a Senior Institutional Market Strategist and Mark Minervini / Stan Weinstein Market Regime Specialist for Indian Equities.
Analyze the following breadth tables, sector heatmaps, and rotation trends to produce an actionable Daily Market Situational Awareness Briefing:
MM: {mm_text}
Heatmap: {heat_text}
Rotation: {rot_text}
    """
    try:
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=[prompt],
            config={"service_tier": "flex", "http_options": {"timeout": 900000}},
        )
        today_str = time.strftime("%Y-%m-%d")
        entry = {"date": today_str, "briefing_md": response.text}
        st.session_state.market_briefings[today_str] = entry
        save_market_briefings(st.session_state.market_briefings)
        return entry
    except Exception:
        return None
