import glob
import json
import os
import smtplib
import time
from urllib.parse import urljoin
from bs4 import BeautifulSoup
from google import genai
import markdown
import requests
import streamlit as st
from modules.state import save_fundamental_reports, save_market_briefings


# ==========================================
# 0. HIGH-SPEED DUAL NETWORK ENGINE
# ==========================================
def fetch_screener_html(url, headers, cookies):
    try:
        r = requests.get(url, headers=headers, cookies=cookies, timeout=6)
        if r.status_code == 200 and "documents" in r.text:
            return r.content
    except Exception:
        pass

    try:
        proxy_url = f"https://api.allorigins.win/raw?url={url}"
        r = requests.get(proxy_url, timeout=10)
        if r.status_code == 200:
            return r.content
    except Exception:
        pass

    return None


def fetch_pdf_direct(url, headers, cookies):
    try:
        r = requests.get(url, headers=headers, cookies=cookies, timeout=12, allow_redirects=True)
        if r.status_code == 200 and b"%PDF" in r.content[:100]:
            return r.content
    except Exception:
        pass

    try:
        proxy_url = f"https://api.allorigins.win/raw?url={url}"
        r = requests.get(proxy_url, timeout=15)
        if r.status_code == 200 and b"%PDF" in r.content[:100]:
            return r.content
    except Exception:
        pass

    return None


# ==========================================
# 1. BULLETPROOF PDF GENERATOR ENGINE
# ==========================================
def create_pdf_bytes(ticker, report_md):
    try:
        from fpdf import FPDF
    except ImportError:
        return report_md.encode("utf-8")

    def sanitize_for_pdf(text):
        if not text:
            return ""
        replacements = {
            "🟢": "[PASS] ",
            "🔴": "[FAIL] ",
            "🟡": "[WATCH] ",
            "⚠️": "[WARN] ",
            "🚀": "[CATALYST] ",
            "⚪": "[N/A] ",
            "🟣": "[REVIEW] ",
            "📊": "",
            "🏥": "",
            "📈": "",
            "🔥": "",
            "📋": "",
            "🧠": "",
            "⭐": "",
            "🎯": "[TARGET] ",
            "🚨": "[CIRCUIT] ",
            "₹": "Rs. ",
            "—": "-",
            "–": "-",
            "“": '"',
            "”": '"',
            "‘": "'",
            "’": "'",
            "•": "-",
            "…": "...",
            "**": "",  
            "__": "",  
            "* ": "- ", 
        }
        for k, v in replacements.items():
            text = text.replace(k, v)
        return text.encode("latin-1", "replace").decode("latin-1")

    class PDF(FPDF):
        def header(self):
            self.set_font("Helvetica", "B", 10)
            self.set_text_color(100, 100, 100)
            self.cell(0, 8, sanitize_for_pdf(f"MINERVINI FUNDAMENTAL AI REPORT - {ticker}"), ln=True, align="R")
            self.line(10, 16, 200, 16)
            self.ln(4)

        def footer(self):
            self.set_y(-15)
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(128, 128, 128)
            self.cell(0, 10, sanitize_for_pdf(f"Page {self.page_no()} | Generated by India Equities Screener Studio"), align="C")

    try:
        pdf = PDF()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)

        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(0, 8, sanitize_for_pdf(f"{ticker} Fundamental Analysis Report"), ln=True, align="L")
        pdf.ln(2)

        pdf.set_font("Helvetica", size=9)
        for line in report_md.split("\n"):
            line_str = sanitize_for_pdf(line.strip())
            if not line_str:
                pdf.ln(1.5)
                continue
            if line_str.startswith("#### ") or line_str.startswith("### "):
                pdf.set_font("Helvetica", "B", 11)
                pdf.set_text_color(20, 50, 120)
                pdf.cell(0, 6, line_str.replace("#", "").strip(), ln=True)
                pdf.set_font("Helvetica", size=9)
                pdf.set_text_color(0, 0, 0)
            elif line_str.startswith("## ") or line_str.startswith("# "):
                pdf.set_font("Helvetica", "B", 12)
                pdf.set_text_color(15, 23, 42)
                pdf.cell(0, 7, line_str.replace("#", "").strip(), ln=True)
                pdf.set_font("Helvetica", size=9)
                pdf.set_text_color(0, 0, 0)
            else:
                pdf.multi_cell(0, 4.5, line_str)
                pdf.ln(0.5)

        return bytes(pdf.output())
    except Exception:
        return report_md.encode("utf-8")


# ==========================================
# 2. GEMINI FUNDAMENTAL AI ANALYST ENGINE
# ==========================================
def run_gemini_fundamental_analysis(
    ticker_input, reports_store=None, status_log=None
):
    gemini_key = st.secrets.get("GEMINI_API_KEY", "")
    screener_sid = st.secrets.get("SCREENER_SESSION_ID", "")
    email_addr = st.secrets.get("EMAIL_ADDRESS", "")
    email_pass = st.secrets.get("EMAIL_APP_PASSWORD", "")

    if not gemini_key:
        if status_log:
            status_log.error("❌ Missing GEMINI_API_KEY in Streamlit Secrets!")
        return None

    client = genai.Client(api_key=gemini_key)

    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
        "Referer": "https://www.screener.in/",
    }
    cookies = {"sessionid": screener_sid}

    clean_ticker = (
        ticker_input.split(":")[-1].strip().upper()
        if ":" in str(ticker_input)
        else str(ticker_input).strip().upper()
    )
    download_dir = "documents"
    os.makedirs(download_dir, exist_ok=True)
    for f in glob.glob(f"{download_dir}/*"):
        os.remove(f)

    url = f"https://www.screener.in/company/{clean_ticker}/consolidated/"

    try:
        if status_log:
            status_log.write(f"⚡ **{clean_ticker}:** Fetching latest Screener document links...")

        html_content = fetch_screener_html(url, headers, cookies)
        if not html_content:
            if status_log:
                status_log.error(f"❌ **{clean_ticker}:** Could not access Screener.in page.")
            return None

        soup = BeautifulSoup(html_content, "html.parser")
        documents_section = soup.find(id="documents")

        if not documents_section:
            if status_log:
                status_log.warning(f"⚠️ **{clean_ticker}:** No documents section found on Screener.in.")
            return None

        transcripts, ppts = [], []
        links = documents_section.find_all("a", href=True)

        for link in links:
            href = link["href"]
            text = link.get_text(strip=True).lower()

            if text == "transcript":
                transcripts.append(href)
            elif text == "ppt":
                ppts.append(href)

        target_docs = []
        if transcripts:
            target_docs.append(("Latest Transcript", transcripts[0]))
        if ppts:
            target_docs.append(("Latest PPT", ppts[0]))

        if not target_docs:
            if status_log:
                status_log.warning(f"⚠️ **{clean_ticker}:** No Transcripts or PPTs listed on Screener.")
            return None

        state_count = 0
        for doc_type, href in target_docs:
            full_url = href if href.startswith("http") else urljoin("https://www.screener.in", href)
            
            pdf_bytes = fetch_pdf_direct(full_url, headers, cookies)
            if pdf_bytes:
                file_path = os.path.join(download_dir, f"screener_doc_{state_count + 1}.pdf")
                with open(file_path, "wb") as f:
                    f.write(pdf_bytes)
                state_count += 1
                if status_log:
                    status_log.write(f"  -> Downloaded {doc_type} (< 1 sec)")

        pdf_files = glob.glob(f"{download_dir}/*.pdf")
        if not pdf_files:
            if status_log:
                status_log.error(f"❌ **{clean_ticker}:** Could not download valid official PDFs.")
            return None

        if status_log:
            status_log.write(f"🤖 **{clean_ticker}:** Uploading official ground-truth documents to Gemini 2.5 Flash...")

        uploaded_files = []
        for file_path in pdf_files:
            uploaded_file = client.files.upload(file=file_path)
            uploaded_files.append(uploaded_file)

        for f in uploaded_files:
            while True:
                file_info = client.files.get(name=f.name)
                if "ACTIVE" in str(file_info.state).upper():
                    break
                time.sleep(1)

        if status_log:
            status_log.write(f"🧠 **{clean_ticker}:** Running Minervini AI Fundamental Analysis...")

        prompt = """
You are an uncompromising, strict Mark Minervini-style fundamental analyst. Your sole objective is to analyze the provided Investor Presentations and Earnings Call Transcripts to determine if the company meets Minervini's "Superperformance" criteria.

### DATA & GROUND TRUTH RULES
1. Rely ONLY on the uploaded documents and consider ONLY consolidated financial figures.
2. Do not speculate, calculate unstated assumptions, or fill gaps from external knowledge.
3. If any metric or fact is missing from the document, write explicitly: "Not available in uploaded documents."

### STRICT CATALYST & VERDICT RULES (CRITICAL)
- **NO CATALYST = NO PASS:** Even if YoY earnings and sales growth are >20%, you CANNOT award a 🟢 PASS if there is no explicit, forward-looking fundamental catalyst identified in the transcripts or presentations. If growth is strong but no catalyst/trigger is found, the maximum grade is 🟡 WATCHLIST.
- **SECTOR-ADAPTIVE CATALYST SEARCH:** Automatically adjust the catalyst criteria based on the company's business model:
  - *Manufacturing / Auto / Infra:* CapEx completion, plant commissioning, order book growth, raw material margin relief.
  - *Financials / Banks / NBFCs:* Credit/loan growth acceleration, Net Interest Margin (NIM) expansion, sharp drops in NPAs, strong AUM growth.
  - *Tech / IT / SaaS:* Large deal wins (TCV), client additions, utilization/margin recovery, geographic expansion.
  - *Consumer / FMCG / Retail:* Volume growth acceleration (not just price-led), Same-Store Sales Growth (SSSG), store count expansion.
  - *Pharma / Healthcare:* US FDA approvals, new launches, hospital bed capacity additions, ARPOB growth.
  - *Platforms / Exchanges:* Market share expansion, active user growth, transaction volume surges.
- **FORWARD-LOOKING vs. BACKWARD-LOOKING:** Prioritize forward-looking triggers (management guidance, upcoming launches, margin expansions, pipeline) found in recent Earnings Calls over historical reasons in old reports.
- **Base Verdict ONLY on Available Data:** Do not penalize missing data points, but strictly enforce the presence of a tangible growth catalyst.

---

### OUTPUT FORMAT & VISUAL HIERARCHY

#### 1. HEADER & INSTANT VERDICT
Provide the company name and an instant decision verdict:
- **MINERVINI FUNDAMENTAL VERDICT:** [Insert 🟢 PASS / 🟡 WATCHLIST / 🔴 FAIL]
- **🚀 PRIMARY CATALYST / BREAKOUT TRIGGER:** [State in 1-2 BOLD sentences the exact forward-looking trigger driving this stock. If NONE found, state: "⚠️ NO CLEAR FORWARD CATALYST DETECTED"].
- **VERDICT LOGIC:** [Provide a 1-2 sentence justification for the overall verdict].
  - 🟢 **PASS:** Available YoY Sales & EPS > 20%, positive Code 33 acceleration, AND a clear, validated forward catalyst.
  - 🟡 **WATCHLIST:** Strong growth but NO clear catalyst, a minor confirmed red flag, OR a Catalyst Override applied.
  - 🔴 **FAIL:** Confirmed Sales/EPS growth < 20%, decelerating growth, or major red flags without a massive catalyst.

#### 2. SUPERPERFORMANCE SCORECARD
Present this quick-scan summary table (Use "N/A - Not in Document" if missing):

| Core Pillar | Status | Key Metric / Reason |
| :--- | :---: | :--- |
| **1. Growth Velocity (Code 33)** | [🟢 / 🟡 / 🔴 / ⚪ N/A] | [1-line summary of EPS, Sales, and Net Margin acceleration] |
| **2. Forward Catalyst & Triggers** | [🟢 / 🟡 / 🔴 / ⚪ N/A] | [1-line summary of sector-specific catalyst from Concalls/PPTs] |
| **3. Earnings Quality & Red Flags**| [🟢 / 🟡 / 🔴 / ⚪ N/A] | [1-line summary of receivables, inventory, or cash flow] |

#### 3. BOTTOM LINE UP FRONT (BLUF)
- **Top Fundamental Strengths (from available data):**
  - [Bullet 1]
  - [Bullet 2]
  - [Bullet 3]
- **Top Red Flags / Concerns (from available data):**
  - [Bullet 1]
  - [Bullet 2]
  - [Bullet 3]

---

### DETAILED ANALYSIS BREAKDOWN

Use visual status icons at the start of each bullet:
- 🟢 Clear Pass
- 🔴 Fail/Red Flag
- 🟡 Mixed / Catalyst Override Applied
- ⚠️ Warning/Watch
- ⚪ Not available in document

Bold ONLY key metrics, figures, and definitive "Yes/No" answers.

#### SECTION 1: Growth Velocity (The Engine)
* **Latest Quarter YoY Growth:** Is EPS and Sales growth **>20%**? State exact % values.
* **Code 33 Acceleration:** Are EPS, Sales, AND Net Margins accelerating compared to prior 2-3 quarters or same quarter last year? (**Yes / No / Data Missing**)
* **Margin Dynamics:** Are Net and Operating Profit Margins expanding or contracting YoY?
* **Management Guidance:** Did management raise or confirm strong future outlook/guidance in recent Earnings Calls?
* **Annual Track Record:** Annual EPS growth rate? Are current FY estimates projected to reach a new all-time high?

#### SECTION 2: Sector-Adaptive Catalyst & Forward Triggers (Concall & PPT Extraction)
* **Primary Sector Catalyst:** Identify the primary growth driver based on the industry (e.g., CapEx/Order Book for Industrial; NIM/Credit growth for Banks; Deal wins/Margins for IT; Volume/SSSG/Stores for Retail; FDA/Launches for Pharma).
* **Catalyst Magnitude & Timeline:** Is this a game-changing trigger taking effect in the next 1-4 quarters? State exact management commentary or guidance.
* **Institutional Sponsorship (FII/DII Trend):** Did FII, DII, or Mutual Fund shareholding increase in the most recent quarter compared to the previous quarter? (Yes / No / Data Missing)
* **Market Leadership:** Is the company a market leader (#1 or #2 in its niche) or gaining market share?
* **Competitive Advantage & Scalability:** Is the growth model scalable without excessive capital burn?

#### SECTION 3: Quality of Earnings & Red Flags
* ⚠️ **Inventory vs. Sales Growth:** Is inventory (especially finished goods) growing faster than sales? State exact growth rate comparison if present (Mark N/A for Banks/Services).
* ⚠️ **Receivables vs. Sales Growth:** Are accounts receivable growing faster than sales?
* **Source of Profit:** Is EPS driven by **Top Line revenue**, or by cost-cutting, tax benefits, or "Other Income"?
* **Tax Rate Distortion:** Was there an artificial boost to EPS from a lower effective tax rate?
* **Cash Flow vs. Earnings:** Has Operating Cash Flow (CFO) diverged negatively from Net Profit?
* **Debt Load & Solvency:** What is the total debt load (or NPA profile for financials), and can cash flows easily service it?
"""

        max_retries = 3
        response = None
        
        for attempt in range(max_retries):
            try:
                response = client.models.generate_content(
                    model="gemini-2.5-flash",
                    contents=[prompt] + uploaded_files,
                    config={"service_tier": "flex", "http_options": {"timeout": 900000}},
                )
                break  # Exit loop if successful
            except Exception as e:
                err_str = str(e).upper()
                
                # Check for Google API Capacity Issues (503 / High Demand)
                if "503" in err_str or "UNAVAILABLE" in err_str or "HIGH DEMAND" in err_str:
                    if attempt < max_retries - 1:
                        wait_time = (attempt + 1) * 5
                        if status_log:
                            status_log.warning(f"⚠️ Google Gemini API is overloaded (503). Retrying in {wait_time}s...")
                        time.sleep(wait_time)
                        continue
                    else:
                        raise Exception("Google Gemini API is currently unavailable due to high global demand. Please try again later.")
                
                # Check for Document Size Limits (400 / Too Many Tokens)
                elif "TOKENS ALLOWED" in err_str or "400" in err_str:
                    if status_log:
                        status_log.warning(f"⚠️ OVERLOAD: {clean_ticker} documents are too massive. Retrying with fewer files...")
                    reduced_files = uploaded_files[:1]
                    try:
                        response = client.models.generate_content(
                            model="gemini-2.5-flash",
                            contents=[prompt] + reduced_files,
                            config={"service_tier": "flex", "http_options": {"timeout": 900000}},
                        )
                        break
                    except Exception as fallback_e:
                        raise fallback_e
                
                # Unhandled exceptions raise immediately
                else:
                    raise e
        
        if not response:
            raise Exception("Failed to generate report after retries.")

        analysis_text = response.text

        verdict_line = ""
        for line in analysis_text.upper().split("\n"):
            if "MINERVINI FUNDAMENTAL VERDICT:" in line or "VERDICT:" in line:
                verdict_line = line
                break

        if "PASS" in verdict_line or "🟢" in verdict_line:
            verdict = "🟢 PASS"
        elif "WATCHLIST" in verdict_line or "🟡" in verdict_line:
            verdict = "🟡 WATCHLIST"
        elif "FAIL" in verdict_line or "🔴" in verdict_line:
            verdict = "🔴 FAIL"
        else:
            verdict = "⚪ Review Needed"

        today_str = time.strftime("%Y-%m-%d")
        report_entry = {
            "ticker": clean_ticker,
            "verdict": verdict,
            "date": today_str,
            "report_md": analysis_text,
        }

        if reports_store is not None:
            reports_store[clean_ticker] = report_entry
            save_fundamental_reports(reports_store)
        else:
            st.session_state.fundamental_reports[clean_ticker] = report_entry
            save_fundamental_reports(st.session_state.fundamental_reports)

        if status_log:
            status_log.write(
                f"✅ **{clean_ticker}:** Analysis complete! Verdict ->"
                f" **{verdict}** (Saved to Gist)"
            )

        if email_addr and email_pass:
            try:
                from email.mime.multipart import MIMEMultipart
                from email.mime.text import MIMEText

                html_text = markdown.markdown(
                    analysis_text, extensions=["tables"]
                )
                subject = f"{clean_ticker} - {verdict}"

                msg = MIMEMultipart("alternative")
                msg["From"] = email_addr
                msg["To"] = email_addr
                msg["Subject"] = subject

                part1 = MIMEText(analysis_text, "plain")
                part2 = MIMEText(html_text, "html")
                msg.attach(part1)
                msg.attach(part2)

                server = smtplib.SMTP("smtp.gmail.com", 587)
                server.starttls()
                server.login(email_addr, email_pass)
                server.send_message(msg)
                server.quit()
                if status_log:
                    status_log.write(f"📧 Email report delivered for {clean_ticker}.")
            except Exception as mail_err:
                if status_log:
                    status_log.write(f"⚠️ Email dispatch warning: {mail_err}")

        return report_entry
        
    except Exception as e:
        if status_log:
            status_log.error(f"❌ **{clean_ticker}:** Analysis failed -> {e}")
        return None


# ==========================================
# 3. REPORT MODAL DIALOG
# ==========================================
@st.dialog("🧠 Minervini Fundamental AI Analyst", width="large")
def show_fundamental_modal(ticker_symbol):
    clean_sym = (
        ticker_symbol.split(":")[-1].strip().upper()
        if ":" in str(ticker_symbol)
        else str(ticker_symbol).strip().upper()
    )
    rep = st.session_state.fundamental_reports.get(clean_sym)

    if not rep:
        st.info(
            f"No stored report for **{clean_sym}**. Check its row in the table"
            " below and click 'Analyze Selected'!"
        )
    else:
        st.subheader(f"📊 {clean_sym} — {rep.get('verdict', 'N/A')}")
        st.caption(
            f"📅 Generated On: **{rep.get('date', 'N/A')}** | 💡 Official Document Analysis"
        )
        st.markdown("---")
        st.markdown(rep.get("report_md", ""))
        st.markdown("---")

        col_pdf, col_re = st.columns([1, 1])

        with col_pdf:
            pdf_bytes = create_pdf_bytes(clean_sym, rep.get("report_md", ""))
            st.download_button(
                label=f"📥 Download {clean_sym} Report (PDF)",
                data=pdf_bytes,
                file_name=f"{clean_sym}_Minervini_Fundamental_Report.pdf",
                mime="application/pdf",
                use_container_width=True,
                type="primary",
            )

        with col_re:
            if st.button(
                "🔄 Re-Analyze & Overwrite (Quarterly Refresh)",
                type="secondary",
                use_container_width=True,
            ):
                with st.spinner(
                    f"📡 Fetching latest official PDFs & replacing {clean_sym}"
                    " report..."
                ):
                    updated_rep = run_gemini_fundamental_analysis(
                        clean_sym, st.session_state.fundamental_reports
                    )
                    if updated_rep:
                        st.success(
                            "✅ Old report replaced with latest quarterly data!"
                        )
                        st.rerun()


# ==========================================
# 4. GEMINI AI SITUATIONAL AWARENESS ENGINE
# ==========================================
def run_gemini_market_awareness(
    df_mm, df_heat, df_rot, scan_summary_dict=None, status_log=None
):
    gemini_key = st.secrets.get("GEMINI_API_KEY", "")
    if not gemini_key:
        if status_log:
            status_log.error("❌ Missing GEMINI_API_KEY in Streamlit Secrets!")
        return None

    client = genai.Client(api_key=gemini_key)

    mm_text = "No Market Monitor Data"
    if not df_mm.empty:
        mm_slice = df_mm.head(10).to_string(index=False)
        mm_text = f"NSE Market Monitor (Last 10 Trading Days):\n{mm_slice}"

    heat_text = "No Sector Heatmap Data"
    if not df_heat.empty:
        heat_slice = df_heat.to_string(index=False)
        heat_text = f"27-Sector CAN SLIM RS Heatmap & Rank Velocities:\n{heat_slice}"

    rot_text = "No Rotation Tracker Data"
    if not df_rot.empty:
        rot_slice = df_rot.head(10).to_string(index=False)
        rot_text = (
            "65-Day Historical Sector RS Ranks (Last 10 Days Trend):\n"
            f" {rot_slice}"
        )

    scan_text = "No Active Screener Scan Summary Available"
    if scan_summary_dict:
        sec_str = json.dumps(scan_summary_dict.get("sectors", {}), indent=2)
        ind_str = json.dumps(scan_summary_dict.get("industries", {}), indent=2)
        scan_text = (
            f"Active Screener Scan Leadership Breakdown:\n- Top Sectors passing"
            f" filters:\n{sec_str}\n- Top Basic Industries passing"
            f" filters:\n{ind_str}"
        )

    prompt = f"""
You are a Senior Institutional Market Strategist and Mark Minervini / Stan Weinstein Market Regime Specialist for Indian Equities (NSE/BSE).

Your sole objective is to analyze the provided multi-day market breadth tables, sector relative strength heatmaps, 65-day rotation rank trends, and active CAN SLIM screener setup concentrations to produce an uncompromising, actionable **Daily Market & Sector Situational Awareness Briefing**.

---

### QUANTITATIVE DATA INPUTS:

{mm_text}

---

{heat_text}

---

{rot_text}

---

{scan_text}

---

### MANDATORY REPORT TEMPLATE & STRUCTURAL REQUIREMENTS:

Generate the report following this exact markdown template structure without skipping any section:

# 🏥 DAILY MARKET & SECTOR SITUATIONAL AWARENESS BRIEFING

#### 1. EXECUTIVE SUMMARY & MARKET REGIME
- **CURRENT MARKET REGIME:** [Select ONE: 🟢 CONFIRMED UPTREND / 🟡 POWERED UPTREND (CAUTION) / 🟠 RANGEBOUND / CHOPPY / 🔴 MARKET UNDER PRESSURE / BEARISH REVERSAL]
- **SETUP SUITABILITY MATRIX:**
  - 🚀 **Momentum Breakout Setups:** [HIGHLY CONDUCTIVE / SELECTIVE (HIGH QUALITY ONLY) / AVOID]
  - 📉 **Pullback / Re-test Setups:** [HIGHLY CONDUCTIVE / SELECTIVE / AVOID]
  - 🔄 **Consolidation / Base Setups:** [HIGHLY CONDUCTIVE / SELECTIVE / AVOID]
- **OVERALL MARKET STATE SUMMARY:** [3-4 sentences synthesizing price action, breadth thrusts, A/D ratio, and % of stocks above key moving averages over the past 5-10 days].

---

#### 2. MARKET BREADTH & HEALTH SYNTHESIS
- **Trend & Moving Average Participation:** Analyze the trend in stocks >20 EMA, >50 SMA, and >200 SMA.
- **Thrust & Volume Expansion:** Interpret the 5-Day & 10-Day Thrust Ratios, A/D Ratio, and Volume Breadth.
- **Expansion vs. Contraction:** Evaluate 52W Highs vs. 52W Lows and 4% Up vs. Down movers over the past week.

---

#### 3. SECTOR MOMENTUM & ROTATION RADAR
- 🟢 **LEADERSHIP SECTORS (Top Focus for Long Setups):** Detail the top 3-5 sectors ranking #1-5 with positive rank velocity and RS > benchmark.
- 🚀 **EMERGING / ACCELERATING SECTORS:** Detail sectors jumping ranks rapidly in 5D/10D/21D rank velocity.
- ⚠️ **FADING / WEAKENING SECTORS:** Detail sectors dropping in relative strength or breaking below 50 SMA.
- 🔴 **AVOID / BEARISH SECTORS:** Bottom ranked sectors or sectors showing sharp negative rank velocity.

---

#### 4. ACTIVE SCREENER SCAN CLUSTER ANALYSIS
- **Sector Concentration:** Analyze where the highest percentage of passing stocks originate based on the scan summary data.
- **Industry Sub-Clusters:** Identify specific basic industries showing stock setup clusters (e.g., Industrial Manufacturing, Capital Goods, Pharma).

---

#### 5. ACTIONABLE NEXT-DAY EXECUTION PLAN
- 🛡️ **Allowed Risk Per Trade:** [State exact equity risk rule, e.g., 0.5% - 0.75% per trade].
- 💰 **Maximum Portfolio Deployment / Cash Buffer:** [State cash allocation rule, e.g., 80%-100% deployed vs 30% cash buffer].
- 🎯 **Primary Focus Sectors & Industries for Tomorrow:** [List exact 2-3 sectors and basic industries to screen for buys].
- 🚨 **Key Invalidation Levels & Danger Triggers:** [State exact breadth or Nifty 500 thresholds that would signal stopping new buys].
"""

    max_retries = 3
    response = None
    
    for attempt in range(max_retries):
        try:
            response = client.models.generate_content(
                model="gemini-2.5-flash",
                contents=[prompt],
                config={"service_tier": "flex", "http_options": {"timeout": 900000}},
            )
            break
        except Exception as e:
            err_str = str(e).upper()
            if "503" in err_str or "UNAVAILABLE" in err_str or "HIGH DEMAND" in err_str:
                if attempt < max_retries - 1:
                    wait_time = (attempt + 1) * 5
                    if status_log:
                        status_log.warning(f"⚠️ Google API overloaded (503). Retrying in {wait_time}s...")
                    time.sleep(wait_time)
                    continue
                else:
                    if status_log:
                        status_log.error("❌ Google Gemini API is currently unavailable due to high global demand. Please try again later.")
                    return None
            else:
                if status_log:
                    status_log.error(f"❌ Failed to generate Market Briefing -> {e}")
                return None

    if not response:
        return None

    try:
        briefing_text = response.text
        today_str = time.strftime("%Y-%m-%d")

        entry = {
            "date": today_str,
            "briefing_md": briefing_text,
        }

        st.session_state.market_briefings[today_str] = entry
        save_market_briefings(st.session_state.market_briefings)

        if status_log:
            status_log.write(
                f"✅ **Market Briefing Generated for {today_str}** (Saved to Gist)"
            )

        return entry
    except Exception as e:
        if status_log:
            status_log.error(f"❌ Failed to parse Market Briefing -> {e}")
        return None
